#!/bin/bash


# displays current date and time
date;

# displays current uptime for node
echo "Uptime: "
uptime

# displays users currently connected to the node
echo "Currently Connected: "
w
echo "============================"

# displays the last 3 users to login to the node
echo "Last Logins: "
last -a | head -3
echo "============================"

# displays memory and disk usage
echo "Disk and Memory usage: "
df -h | xargs | awk '{print "Free/Total Disk: " $11 " / " $9}'
echo "============================"

# displays OOM errors for current node
start_log='head -1 /var/log/messages | cut -c 1-12'
oom='grep -ci kill  /var/logs/messages'
echo -n "OOM errors since $start_log :" $oom
echo ""
echo "============================"

# displays top processes on node
echo "Utilization of most expensive processes: "
top -b | head -3
echo 
top -b | head -10 | tail -4
echo "============================"

# displays open tcp ports
echo "Open TCP ports: "
nmap -p- -T4 127.0.0.1
echo "============================"

# displays current connections to the node
echo "Current Connections: "
ss -s
echo "============================"

# displays processes running on the node
echo "Processes: "
ps auxf --width=200
echo "============================"

# displays virtual memory stats
echo "vmstat: "
vmstat 1 5
